#!/usr/bin/env python3
"""Render and lint the human workflow view from the machine authority."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


SPEC_ROOT = Path(__file__).resolve().parent.parent
WORKFLOW = SPEC_ROOT / "workflow" / "workflow.json"
REGISTRY = SPEC_ROOT / "workflow" / "document-registry.json"
OUTPUT = SPEC_ROOT / "1-Master" / "Article-Workflow-v2.md"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def render() -> str:
    workflow = load(WORKFLOW)
    lines = [
        "<!-- GENERATED by scripts/render_workflow_docs.py; edit workflow/workflow.json instead. -->",
        "",
        f"# Article Workflow v{workflow['workflow_version']}",
        "",
        "This is the generated human view of the machine-readable authority. It is not an independent rule source.",
        "",
        "## Precedence",
        "",
        "```text",
        " > ".join(workflow["precedence"]),
        "```",
        "",
        "## Capability boundary",
        "",
        workflow["capability_boundary"],
        "",
        "## State machine",
        "",
        "| State | Actor | Objective | Gate | Passes to | Repair returns to | Attempts | Timeout | Side effects |",
        "|---|---|---|---|---|---|---:|---:|---|",
    ]
    for state in workflow["states"]:
        lines.append(
            "| {id} | {actor} | {objective} | {gate} | {next_on_pass} | {repair_state} | {max_attempts} | {timeout_seconds}s | {side_effect_class} |".format(
                **{key: ("—" if value is None else str(value).replace("|", "\\|")) for key, value in state.items()}
            )
        )
    lines += ["", "## State recovery policy", ""]
    for state in workflow["states"]:
        lines.append(f"- **{state['id']}:** {state['retry_policy']} {state['escalation_condition']}")
    lines += ["", "## Post-publication lifecycle states", ""]
    for state in workflow.get("lifecycle_states", []):
        redirect = " Redirect verification is required." if state.get("requires_redirect_check") else ""
        lines.append(f"- **{state['id']}:** {state['objective']}{redirect}")
    lines += ["", "## Gate outcomes", ""]
    for outcome in workflow["gate_outcomes"]:
        lines.append(f"- `{outcome}`")
    lines += ["", "## Stable rules", ""]
    for rule in workflow["rules"]:
        lines.append(f"- **{rule['id']} ({rule['level']}):** {rule['text']}")
    lines += [
        "",
        "## Gate ownership",
        "",
        "Hard gates are decided by code or an explicit scoped approval; a model cannot waive them. Soft gates are decided by the operator or a calibrated evaluator and retain passage-specific findings.",
        "",
        "**Hard:** " + ", ".join(f"`{item}`" for item in workflow["gates"]["hard"]),
        "",
        "**Soft:** " + ", ".join(f"`{item}`" for item in workflow["gates"]["soft"]),
        "",
    ]
    return "\n".join(lines)


def lint_registry() -> list[str]:
    registry = load(REGISTRY)
    failures: list[str] = []
    for item in registry["non_authoritative_documents"]:
        path = SPEC_ROOT / item["path"]
        if not path.is_file():
            failures.append(f"missing registered document: {item['path']}")
            continue
        text = path.read_text(encoding="utf-8")
        expected = {
            f"article_flow_document_status: {item['status']}",
            "article_flow_authority: false",
            f"article_flow_removal_version: \"{item['removal_version']}\"",
        }
        for marker in expected:
            if marker not in text[:800]:
                failures.append(f"{item['path']}: missing metadata marker {marker!r}")
    for path_value in registry["authoritative_controls"]:
        if not (SPEC_ROOT / path_value).is_file():
            failures.append(f"missing authoritative control: {path_value}")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failures = lint_registry()
    expected = render()
    if args.write:
        OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    elif not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
        failures.append("generated workflow view is stale; run scripts/render_workflow_docs.py --write")
    if failures:
        for failure in failures:
            print(f"FAIL: {failure}", file=sys.stderr)
        return 1
    print("workflow documentation is consistent")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
